---
# tasks file for vector-role
  - name: Install Vector | YUM install
    become: true
    ansible.builtin.yum:
      name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm
      state: present
    tags: vector-install
    notify: Start vector

  - name: Configure Vector | Template config
    become: true
    ansible.builtin.template:
      src: vector.yml.j2
      mode: "0644"
      dest: "{{ vector_config_dir }}/vector.yaml"
    tags: vector-config
    notify: Restart vector
