---
# handlers file for vector-role
  - name: Start vector
    become: true
    ansible.builtin.service:
      name: vector
      enabled: true
      state: started
  - name: Restart vector
    become: true
    ansible.builtin.service:
      name: vector
      state: restarted