---
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: centos
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  # - name: oraclelinux
  #   image: docker.io/oraclelinux:8
  #   pre_build_image: true
  # - name: ubuntu
  #   image: docker.io/ubuntu:latest
  #   pre_build_image: true
verifier:
  name: ansible